# Generated by Django 6.0.2 on 2026-02-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_goal_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='future_profile',
        ),
        migrations.AddField(
            model_name='roadmapphase',
            name='completion_criteria',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
